# Generated by Django 4.2.6 on 2023-11-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_details_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="role",
            field=models.CharField(default="User", max_length=50),
        ),
    ]
