# Generated by Django 4.2.6 on 2023-10-25 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="List_Of_Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("title", models.CharField(max_length=200)),
                ("price", models.FloatField(default=0)),
                ("author", models.CharField(default="Admin", max_length=50)),
                ("date_modified", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
