# Generated by Django 4.2.6 on 2023-10-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doucecravingsnew_app", "0002_catlog_item_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Best_Sellers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("box_image", models.ImageField(upload_to="")),
                ("box_name", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_image", models.ImageField(upload_to="")),
            ],
        ),
    ]
