# Generated by Django 4.2.6 on 2023-11-02 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "doucecravingsnew_app",
            "0005_delete_item_details_list_of_items_date_modified_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="list_of_items",
            name="date_modified",
            field=models.DateField(
                default=datetime.datetime(2023, 11, 2, 3, 14, 35, 211361)
            ),
        ),
        migrations.AlterField(
            model_name="list_of_items",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
