# Generated by Django 4.2.6 on 2023-11-03 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doucecravingsnew_app", "0006_alter_list_of_items_date_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list_of_items",
            name="date_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 3, 0, 41, 42, 228133)
            ),
        ),
    ]
