# Generated by Django 4.2.6 on 2023-11-03 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doucecravingsnew_app", "0008_alter_list_of_items_date_modified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_review", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="list_of_items",
            name="date_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 3, 4, 54, 56, 437232)
            ),
        ),
        migrations.AlterField(
            model_name="list_of_items",
            name="toppings",
            field=models.CharField(
                default="Funfetti,Brownie Crumbles,Chocolate Chips, Oreo Crumbles,M&Ms"
            ),
        ),
    ]
