# Generated by Django 4.2.6 on 2023-11-03 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "doucecravingsnew_app",
            "0009_reviews_alter_list_of_items_date_modified_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="list_of_items",
            name="date_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 3, 4, 57, 16, 893074)
            ),
        ),
    ]
