# Generated by Django 4.2.6 on 2023-11-04 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doucecravingsnew_app", "0011_review_alter_list_of_items_date_modified"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reviews",
        ),
        migrations.AlterField(
            model_name="list_of_items",
            name="date_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 4, 16, 5, 17, 335056)
            ),
        ),
    ]
