# Generated by Django 4.2.6 on 2023-11-05 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doucecravingsnew_app", "0013_reviews_alter_list_of_items_date_modified"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reviews",
        ),
        migrations.AlterField(
            model_name="list_of_items",
            name="date_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 5, 0, 36, 35, 731632)
            ),
        ),
    ]
