# Generated by Django 4.2.6 on 2023-11-11 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doucecravingsnew_app", "0019_list_of_items_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list_of_items",
            name="date_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 11, 22, 20, 53, 207536)
            ),
        ),
    ]
