# Generated by Django 4.2.6 on 2023-11-14 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "doucecravingsnew_app",
            "0023_list_of_items_user_alter_list_of_items_date_modified",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="list_of_items",
            name="user",
        ),
        migrations.AlterField(
            model_name="list_of_items",
            name="date_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 1, 4, 53, 121684)
            ),
        ),
    ]
