# Generated by Django 4.2.6 on 2023-11-14 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doucecravingsnew_app", "0024_remove_list_of_items_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list_of_items",
            name="date_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 1, 12, 26, 720990)
            ),
        ),
    ]
