# Generated by Django 4.2.6 on 2023-11-14 01:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doucecravingsnew_app", "0026_alter_list_of_items_date_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="list_of_items",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="list_of_items",
            name="date_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 1, 21, 25, 680347)
            ),
        ),
    ]
